export const queryKeys = {
  executiveMetrics: ['dashboard', 'executive'] as const,
  financialChart: (months = 6) => ['dashboard', 'financial-chart', months] as const,
  commercialMetrics: ['dashboard', 'commercial'] as const,
  operationalMetrics: ['dashboard', 'operational'] as const,
  financialDashboard: ['dashboard', 'financial'] as const,
  headerMetrics: ['layout', 'header-kpis'] as const,
  sidebarBadges: ['layout', 'sidebar-badges'] as const,
  recentActivities: (limit: number) => ['layout', 'activities', limit] as const,
  notifications: (userId: string) => ['layout', 'notifications', userId] as const,
  criticalStockCount: ['metrics', 'critical-stock'] as const,
  financialSummary: ['financial', 'summary'] as const,
  financialSettings: ['financial', 'settings'] as const,
  financialTransactions: (page: number, filter: string) => ['financial', 'transactions', page, filter] as const,
  lumberCreditStats: ['lumber-credit', 'stats'] as const,
  lumberCreditAllMovements: ['lumber-credit', 'all-movements'] as const,
  lumberCreditBalancesByClient: ['lumber-credit', 'balances-by-client'] as const,
  lumberCreditSettings: ['lumber-credit', 'settings'] as const,
  lumberCreditMovements: (filters: Record<string, unknown>, page: number) =>
    ['lumber-credit', 'movements', filters, page] as const,
  clients: (page: number, search: string) => ['clients', page, search] as const,
  lookupClients: ['lookups', 'clients'] as const,
  lookupOrders: ['lookups', 'orders'] as const,
  lookupSuppliers: ['lookups', 'suppliers'] as const,
  lookupArchitects: ['lookups', 'architects'] as const,
  lookupMaterials: ['lookups', 'materials'] as const,
  lookupPurchases: ['lookups', 'purchases'] as const,
  lookupEmployeesPayroll: ['lookups', 'employees-payroll'] as const,
  materialCategories: ['settings', 'material-categories'] as const,
  crmLeads: ['crm', 'leads'] as const,
  ordersKanban: ['orders', 'kanban'] as const,
  purchases: ['purchases', 'list'] as const,
  productionOrders: ['production', 'orders'] as const,
  productionOrderOptions: ['production', 'order-options'] as const,
  employees: ['employees', 'list'] as const,
  marketingInvestments: ['marketing', 'investments'] as const,
  marketingInvestmentsPaginated: (year: number, month: number | 'all', page: number) =>
    ['marketing', 'investments', 'paginated', year, month, page] as const,
  internalRequests: (page: number) => ['requests', 'list', page] as const,
  materials: (filters: Record<string, unknown>) => ['materials', 'list', filters] as const,
  lowStockMaterials: ['inventory', 'low-stock'] as const,
  purchasesPaginated: (page: number) => ['purchases', 'paginated', page] as const,
  employeesPaginated: (page: number) => ['employees', 'paginated', page] as const,
  payrollMonth: (month: string) => ['payroll', 'month', month] as const,
  budgetsPaginated: (page: number) => ['budgets', 'paginated', page] as const,
  budgetProposalDefaults: ['budgets', 'proposal-defaults'] as const,
}
